[package]
name = "csgo-gsi"
version = "0.1.0"
authors = ["ling"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3"
anyhow = "1.0.37"
serde = "1.0"
serde_json = "1.0"
actix-cors = "0.5.4"

